Repository bldrs-ai/Share, pull requests merged in 2022-08, with the labels that each got.

#300 Notes: restore metadata header on comments.
  package.json
  src/Components/IssueCard.jsx
  src/Components/IssueCard.test.jsx
Labels: bug

#297 Tweaks for local serving
  package.json
Labels: bug

#299 Upgrade NPMs
  package.json
  src/index.jsx
  yarn.lock
Labels: code

#302 fix formatting issue from the storybook PR (#290)
  src/Components/Dialog_redesign.jsx
  src/Components/InputBar.jsx
  src/stories/buttons/RectangularButton.stories.jsx
  src/stories/input/Input.stories.jsx
Labels: code

#321 Lint fixes
  src/BaseRoutes.jsx
  src/Components/AboutControl.jsx
  src/Components/Alert.jsx
  src/Components/Buttons.jsx
  src/Components/Buttons.test.jsx
  src/Components/CameraControl.test.jsx
  src/Components/Dialog.jsx
  src/Components/Dialog_redesign.test.jsx
  src/Components/ExpansionPanel.jsx
  src/Components/GuideControl.jsx
  src/Components/InputBar.jsx
  src/Components/IssueCard.jsx
  src/Components/IssuesControl.jsx
  src/Components/ItemPanelControl.jsx
  src/Components/ItemProperties.jsx
  src/Components/ItemPropertiesDrawer.jsx
  src/Components/Logo.jsx
  src/Components/MobileDrawer.jsx
  src/Components/NavPanel.jsx
  src/Components/OpenModelControl.jsx
  src/Components/OperationsGroup.jsx
  src/Components/SampleModelsControl.jsx
  src/Components/SearchBar.jsx
  src/Components/SearchBar.test.jsx
  src/Components/Settings.jsx
  src/Components/ShareControl.jsx
  src/Components/ShortcutsControl.jsx
  src/Components/SideDrawer.jsx
  src/Containers/CadView.jsx
  src/Containers/SearchIndex.js
  src/ShareRoutes.jsx
  src/ShareRoutes.test.jsx
  src/Theme.jsx
  src/Theme.test.jsx
  src/privacy/Privacy.js
  src/privacy/functional.js
  src/stories/buttons/ControlButton.stories.jsx
  src/stories/buttons/FormButton.stories.jsx
  src/stories/buttons/TooltipIconButton.stories.jsx
  src/stories/buttons/TooltipToggleButton.stories.jsx
  src/stories/dialog/Dialog.stories.jsx
  src/utils/TreeUtils.js
  src/utils/cookies.js
  src/utils/debug.js
  src/utils/location.js
  src/utils/math.test.js
  src/utils/mediaQuery.js
  src/utils/mediaQuery.test.js
Labels: code

#324 Lint: Fixed setting model id that broke previous lint fix.
  package.json
  src/Containers/CadView.jsx
Labels: bug, code

#327 Upgrade outdated npms. Found new break in @mui/material for version 5.9.2+ (#325).
  .eslintrc.js
  package.json
  yarn.lock
Labels: code

#328 Remove url camera clear on component load. (restarting PR from post-lint fix).
  package.json
  src/Components/IssuesControl.jsx
Labels: bug

#335 Toggle scene size when drawer expanded; desktop only.
  package.json
  src/Components/SideDrawer.jsx
  src/Containers/CadView.jsx
Labels: feature request

#336 Upgrade: esbuild, eslint, @babel/preset-env, @mui/lab
  config/build.js
  config/common.js
  config/serve.js
  package.json
  yarn.lock
Labels: code

#338 react18: fix render warnings in tests.
  package.json
  src/Components/IssuesControl.test.jsx
  src/Components/ItemProperties.test.jsx
  src/Components/SideDrawer.test.jsx
  src/store/useStore.test.js
  yarn.lock
Labels: code

#333 Fix property set scrolling
  package.json
  src/Components/ItemProperties.jsx
  src/Components/MobileDrawer.jsx
Labels: bug

#348 Tests: Introduce CadView.test.jsx.
  __mocks__/web-ifc-viewer.js
  src/Containers/CadView.test.jsx
Labels: code

#358 Tests: Introduce CadView.test.jsx
  __mocks__/web-ifc-viewer.js
  package.json
  src/Components/CameraControl.jsx
  src/Components/IssuesControl.test.jsx
  src/Components/NavPanel.jsx
  src/Components/NavTree.jsx
  src/Components/SideDrawerPanels.jsx
  src/Containers/CadView.jsx
  src/Containers/CadView.test.jsx
  src/Share.jsx
  src/Theme.jsx
  src/setupTests.js
  src/store/IFCSlice.js
  src/utils/TreeUtils.js
  src/utils/TreeUtils.test.js
  src/utils/assert.js
  src/utils/debug.js
  src/utils/tests.js
  yarn.lock
Labels: code

#354 Bug: Property window is cropped
  src/Components/ItemProperties.jsx
  src/Components/SideDrawer.jsx
  src/Components/SideDrawerPanels.jsx
Labels: UI

#351 Viewer: Change selected and preselected colors
  src/Containers/CadView.jsx
  src/Theme.jsx
Labels: view
