Repository bldrs-ai/Share, pull requests merged in 2023-03, with the labels that each got.

#643 Fix all-tests break introduced in #633 by always requiring canvas.
  src/setupTests.js
Labels: bug

#613 Notes: create+delete
  src/Components/Buttons.jsx
  src/Components/Loader.jsx
  src/Components/NoContent.jsx
  src/Components/Notes/NoteCard.jsx
  src/Components/Notes/NoteCard.test.jsx
  src/Components/Notes/NoteCardCreate.jsx
  src/Components/Notes/NoteCardCreate.test.jsx
  src/Components/Notes/Notes.jsx
  src/Components/Notes/NotesNavBar.jsx
  src/Components/Notes/NotesNavBar.test.jsx
  src/Components/SideDrawer/HorizonResizerButton.jsx
  src/Components/SideDrawer/SideDrawer.jsx
  src/Components/SideDrawer/SideDrawerPanels.jsx
  src/__mocks__/api-handlers.js
  src/assets/icons/Add.svg
  src/assets/icons/AddImage.svg
  src/assets/icons/AddNote.svg
  src/assets/icons/Delete.svg
  src/assets/icons/Link.svg
  src/assets/icons/Pin.svg
  src/assets/icons/Submit.svg
  src/assets/icons/Synch.svg
  src/store/NotesSlice.js
  src/theme/Components.js
  src/utils/GitHub.js
  src/utils/GitHub.test.js
Labels: notes

#645 Add partial opacity background to OperationsGroup to enhance contrast…
  package.json
  src/Components/BranchesControl.jsx
  src/Components/InputBar.jsx
  src/Components/NavPanel.jsx
  src/Components/OperationsGroup.jsx
  src/Components/SearchBar.jsx
  src/Containers/CadView.jsx
Labels: bug

#682 Upgrade cosmos and icon packages, fix breaks
  package.json
  src/Components/About/AboutControl.jsx
  src/Components/About/AboutDialog.fixture.jsx
  src/Components/Dialog.fixture.jsx
  src/Components/Dialog.jsx
  src/Components/buttons/ControlButton.fixture.jsx
  src/ShareMock.jsx
  yarn.lock
Labels: code
