Repository bldrs-ai/Share, pull requests merged in 2023-11, with the labels that each got.

#811 Geometry Coverage
  .cosmos.webpack.js
  bldrs-ai-conway-v0.1.0.tgz
  bldrs-conway-v0.0.1.tgz
  package.json
  tools/esbuild/bundle-analysis.json
  tools/esbuild/common.js
  tools/jest/jest.config.js
  yarn.lock
Labels: feature request

#833 Replace write-new-version for package.json similar to conway.
  package.json
  scripts/updateVersion.mjs
  src/Containers/CadView.test.jsx
  src/utils/version.mjs
  tools/esbuild/bundle-analysis.json
Labels: code

#836 Upgrade bldrs-conway to v0.1.378. Verified it fixes private#3.
  bldrs-ai-conway-v0.1.378.tgz
  package.json
  tools/esbuild/bundle-analysis.json
  yarn.lock
Labels: zz:conway-v0.1.346

#837 Help menu z value fix
  src/Containers/CadView.jsx
Labels: bug

#839 SideDrawer Details
  src/Components/About/AboutControl.jsx
  src/Components/ApplicationError.jsx
  src/Components/Buttons.jsx
  src/Components/ControlsGroup.jsx
  src/Components/ExpansionPanel.jsx
  src/Components/ItemProperties/ItemProperties.jsx
  src/Components/NoContent.jsx
  src/Components/Notes/NotesNavBar.jsx
  src/Components/Notes/NotesNavBar_original.jsx
  src/Components/OpenModelControl.jsx
  src/Components/OperationsGroup.jsx
  src/Components/PanelTitle.jsx
  src/Components/ShareControl.jsx
  src/Components/SideDrawer/SideDrawerPanels.jsx
  src/Components/SnackbarMessage.jsx
  src/Components/UserProfile.jsx
  src/Containers/CadView.jsx
  src/Styles.jsx
  src/theme/Components.js
Labels: UI

#840 Grow Share.svg a tad bit to make it same vertical height as Notes.
  src/assets/icons/Share.svg
Labels: enhancement

#841 Move Properties to back to OperationsGroup
  package.json
  src/Components/ElementGroup.jsx
  src/Components/ElementGroup.test.jsx
  src/Components/OperationsGroup.jsx
  src/Components/OperationsGroup.test.jsx
  src/Containers/CadView.jsx
Labels: enhancement

#842 Props button should be round again.
  package.json
  src/Components/OperationsGroup.jsx
Labels: bug

#857 Disable GA as a workaround for prod freeze bug.
  package.json
  src/Components/About/AboutControl.jsx
  src/privacy/analytics.js
  tools/esbuild/bundle-analysis.json
Labels: bug

#868 Swap build from web-ifc to conway (conway-0.1.408).
  package.json
Labels: deploy

#869 Fix Sample Model link to Schep, which moved to bldrs-ai/test-models
  package.json
  src/Components/OpenModelControl.jsx
Labels: bug

#872 Add run-script-os package via yarn + fix windows compilation
  package.json
  yarn.lock
Labels: enhancement

#866 Add imagine control that includes link to discord channel
  src/Components/Dialog.jsx
  src/Components/HelpControl.jsx
  src/Components/ImagineControl.jsx
  src/Components/ImagineControl.test.jsx
  src/Components/OperationsGroup.jsx
  src/assets/icons/Bot1.svg
  src/assets/icons/Bot2.svg
  src/assets/icons/Bot3.svg
  src/assets/icons/Bot4.svg
  src/theme/Components.js
Labels: UI

#873 Conway update 0.1.408 to 0.1.424 and script updates
  bldrs-ai-conway-0.1.408.tgz
  bldrs-ai-conway-0.1.425.tgz
  bldrs-ai-conway-v0.1.0.tgz
  bldrs-ai-conway-v0.1.378.tgz
  package.json
  tools/esbuild/bundle-analysis.json
  yarn.lock
Labels: enhancement

#870 Introduce a user menu which includes the option to log in and the theme control
  src/Components/LoginMenu.jsx
  src/Components/LoginMenu.test.jsx
  src/Components/OpenModelControl.jsx
  src/Components/OperationsGroup.jsx
Labels: enhancement
