Repository bldrs-ai/Share, pull requests merged in 2023-02, with the labels that each got.

#606 Remove Context/ColorMode.jsx, all handled by theme now.
  package.json
  src/Components/About/AboutGuide.jsx
  src/Components/CutPlaneMenu.jsx
  src/Components/ExtractLevelsMenu.jsx
  src/Components/Logo.jsx
  src/Components/NoContent.jsx
  src/Components/OperationsGroup.jsx
  src/Components/SearchBar.jsx
  src/Components/Settings.jsx
  src/Components/SnackbarMessage.jsx
  src/Components/Toggle.jsx
  src/Containers/CadView.jsx
  src/Context/ColorMode.jsx
  src/Share.jsx
  src/ShareMock.jsx
  src/__mocks__/MockComponent.jsx
  src/theme/Colors.js
  src/theme/Palette.js
  src/theme/Theme.jsx
Labels: code

#629 Fix private branches
  src/Components/BranchesControl.jsx
  src/utils/GitHub.js
Labels: bug

#611 In-scene placemarks
  __mocks__/web-ifc-viewer.js
  package.json
  public/icons/PlaceMark.svg
  src/BaseRoutesMock.test.jsx
  src/Components/CutPlaneMenu.test.jsx
  src/Containers/CadView.jsx
  src/Containers/CadView.test.jsx
  src/Containers/SceneLayer.js
  src/Infrastructure/CustomPostProcessing.js
  src/Infrastructure/IfcViewerAPIExtended.js
  src/Infrastructure/PlaceMark.js
  src/ShareRoutes.test.jsx
  src/assets/README.md
  src/assets/icons/PlaceMark.svg
  src/hooks/usePlaceMark.js
  src/setupTests.js
  src/store/NotesSlice.js
  src/utils/__snapshots__/svg.test.js.snap
  src/utils/constants.js
  src/utils/objects.js
  src/utils/objects.test.js
  src/utils/strings.js
  src/utils/strings.test.js
  src/utils/svg.js
  src/utils/svg.test.js
  yarn.lock
Labels: view, notes
