Repository bldrs-ai/Share, pull requests merged in 2024-04, with the labels that each got.

#1069 Cypress Auth0 Login Mock + Save E2E Tests
  cypress/e2e/profile-100/login.cy.js
  cypress/e2e/versions-100/save-imported-model.cy.js
  cypress/e2e/view-100/initial-model-load-and-view.cy.js
  cypress/screenshots/profile-100/login.cy.js/Profile 100 Login -- when no model is loaded -- Should Login.png
  cypress/screenshots/view-100/initial-model-load-and-view.cy.js/initial-model-load-and-view -- Open model by following a link to a project on Share (e.g. our index.ifc) -- See model centered in page (cookie isFirstTime 1).png
  cypress/screenshots/view-100/initial-model-load-and-view.cy.js/initial-model-load-and-view -- Open model by following a link to a project on Share (e.g. our index.ifc) -- See model centered in page (cookie isFirstTime undefined).png
  cypress/screenshots/view-100/initial-model-load-and-view.cy.js/initial-model-load-and-view -- Open model by following a link to a project on Share (e.g. our index.ifc) -- Visit about permalink.png
  cypress/support/utils.js
  package.json
  src/Components/Open/OpenModelControl.jsx
  src/Components/Open/OpenModelControl.test.jsx
  src/Components/Open/SaveModelControl.jsx
  src/Components/Open/SaveModelControl.test.jsx
  src/Components/Persona/PersonaControl.jsx
  src/__mocks__/api-handlers.js
  src/net/github/Repositories.fixture.js
  tools/esbuild/vars.cypress.js
Labels: enhancement

#1091 esbuild: fix some issues with defines.js and add test
  package.json
  tools/esbuild/defines.js
  tools/esbuild/defines.test.js
Labels: bug

#1092 Yarn serve logging
  package.json
  tools/esbuild/utils.js
Labels: bug

#1094 Remove confusing testId property
  src/Components/Buttons.jsx
  src/Components/Buttons.test.jsx
  src/Components/Open/.#OpenModelControl.test.jsx
  src/Components/Open/OpenModelControl.jsx
  src/Components/Open/SaveModelControl.jsx
  src/Components/Open/Selector.jsx
  src/Components/Open/SelectorSeparator.jsx
  src/Components/SideDrawer/Panel.jsx
Labels: bug

#1065 percy: convert a view-100 test case to percy screenshot
  .github/workflows/end-to-end-tests.yml
  cypress/e2e/view-100/initial-model-load-and-view.cy.js
  cypress/screenshots/profile-100/login.cy.js/Profile 100 Login -- when no model is loaded -- Should Login.png
  cypress/screenshots/view-100/initial-model-load-and-view.cy.js/initial-model-load-and-view -- Open model by following a link to a project on Share (e.g. our index.ifc) -- See model centered in page (cookie isFirstTime 1).png
  cypress/screenshots/view-100/initial-model-load-and-view.cy.js/initial-model-load-and-view -- Open model by following a link to a project on Share (e.g. our index.ifc) -- See model centered in page (cookie isFirstTime undefined).png
  cypress/screenshots/view-100/initial-model-load-and-view.cy.js/initial-model-load-and-view -- Open model by following a link to a project on Share (e.g. our index.ifc) -- Visit about permalink.png
  package.json
  tools/esbuild/vars.cypress.js
  tools/esbuild/vars.dev.js
  tools/esbuild/vars.prod.js
  web-ifc-viewer-1.0.209-bldrs-3.tgz
  web-ifc-viewer-1.0.209-bldrs-7.tgz
  yarn.lock
Labels: enhancement

#1098 gha: remove percy from cypress run
  .github/workflows/end-to-end-tests.yml
Labels: bug

#1099 create-100: introduce e2e tests for imagine
  cypress/e2e/create-100/render-description-of-screenshot.cy.js
Labels: enhancement

#1103 Persona -> Profile. Uniform data-testid in ControlButtons
  cypress/e2e/notes-100/access-notes-list.cy.js
  cypress/e2e/notes-100/note-contains-link-to-github-issue.cy.js
  cypress/e2e/notes-100/select-a-note.cy.js
  cypress/e2e/notes-100/share-a-note.cy.js
  package.json
  src/Components/About/AboutControl.jsx
  src/Components/About/AboutControl.test.jsx
  src/Components/Buttons.jsx
  src/Components/CutPlaneMenu.jsx
  src/Components/Open/OpenModelControl.test.jsx
  src/Components/Open/SaveModelControl.jsx
  src/Components/Open/SaveModelControl.test.jsx
  src/Components/OperationsGroup.jsx
  src/Components/Profile/ProfileControl.jsx
  src/Components/Profile/ProfileControl.test.jsx
  tools/cy-percy.sh
Labels: enhancement

#1104 Refactor view-100 initial model load and view
  cypress/e2e/view-100/initial-model-load-and-view.cy.js
  cypress/support/utils.js
  package.json
  src/Components/About/AboutDialog.jsx
  src/Components/CutPlaneMenu.jsx
  src/Components/Dialog.jsx
Labels: enhancement

#1105 Rename contexts and expects to match story tasks
  cypress/e2e/view-100/initial-model-load-and-view.cy.js
Labels: enhancement

#1107 e2e: view-100: introduce cutplanes
  cypress/e2e/view-100/cutplanes.cy.js
  package.json
  src/Components/CutPlaneMenu.jsx
Labels: enhancement

#1110 1068 imagine subsequent screenshots fail
  cypress/e2e/create-100/imagine.cy.js
  cypress/e2e/create-100/render-description-of-screenshot.cy.js
  cypress/fixtures/candy-cane-bldrs.png
  package.json
  src/Components/Buttons.jsx
  src/Components/Dialog.jsx
  src/Components/ImagineControl.jsx
  t
Labels: bug

#1111 view-100: clear camera on mouse wheel and touchmove
  package.json
  src/Components/CameraControl.jsx
Labels: bug

#1112 1078 default camera autozoom broken
  package.json
  src/Components/CameraControl.jsx
  src/Components/CutPlaneMenu.jsx
  src/Components/ImagineControl.jsx
  src/Components/ShareControl.jsx
  src/Containers/CadView.jsx
  src/store/CameraSlice.js
  src/store/useStore.js
Labels: bug

#1113 more-camera-fixes
  package.json
  src/Components/CameraControl.jsx
  src/Components/CutPlaneMenu.jsx
  src/Components/CutPlaneMenu.test.jsx
  src/Components/ImagineControl.jsx
  src/Components/ShareControl.jsx
  src/Containers/CadView.jsx
  src/store/CameraSlice.js
  src/store/UISlice.js
  src/store/useStore.js
Labels: bug

#1114 Fix #1096
  src/BaseRoutes.jsx
  src/Components/Buttons.jsx
  src/Components/Dialog.jsx
  src/Components/HelpControl.test.jsx
  src/Components/ImagineControl.jsx
  src/Components/Notes/NotesControl.jsx
  src/store/NotesSlice.js
Labels: bug

#1115 Fix #1101
  cypress/e2e/notes-100/share-a-note.cy.js
  src/Components/Notes/NoteCard.jsx
  src/Components/Notes/NotesControl.jsx
  src/Containers/AlertDialogAndSnackbar.jsx
Labels: bug

#1116 Fix #770
  package.json
  src/Components/Notes/Body.jsx
  src/Components/Notes/NoteBody.jsx
  src/Components/Notes/NoteCard.jsx
  src/Components/Notes/NoteContent.jsx
Labels: bug

#1118 notes-100: tweak color for NoteContent links
  package.json
  src/theme/Palette.js
Labels: bug

#1122 Profile 100 - cypress: Theme
  cypress/e2e/profile-100/theme.cy.js
  package.json
  src/Components/Profile/ProfileControl.jsx
Labels: enhancement

#1123 1042-view-100-model-centering-and-view-reset
  cypress/e2e/view-100/model-centering-and-view-reset.cy.js
  package.json
Labels: enhancement

#1125 1043-view-100-shareable-camera-position
  cypress/e2e/view-100/shareable-camera-position.cy.js
  package.json
  src/Components/Dialog.jsx
  src/Components/ShareControl.jsx
  src/Components/ShareControl.test.jsx
  src/Components/Toggle.jsx
  tools/jest/setupTests.js
Labels: enhancement

#1126 Downgrade Cypress 13.2.0
  package.json
  yarn.lock
Labels: enhancement

#1131 Fix 1130-select-element-doesnt-open-nav
  package.json
  src/Components/NavTree/NavTreeControl.jsx
  src/Containers/CadView.jsx
  src/theme/Components.js
  src/utils/assert.js
  src/utils/assert.test.js
Labels: bug

#1132 Profile-100: Login Test + Auth0Proxy
  cypress/e2e/profile-100/login.cy.js
  cypress/support/utils.js
  src/Auth0/Auth0Proxy.js
  src/BaseRoutes.jsx
  src/Components/ControlsGroup.jsx
  src/Components/Notes/NoteCard.jsx
  src/Components/Notes/NoteCardCreate.jsx
  src/Components/Notes/NoteFooter.jsx
  src/Components/Notes/Notes.jsx
  src/Components/Open/OpenModelControl.jsx
  src/Components/Open/SaveModelControl.jsx
  src/Components/Profile/ProfileControl.jsx
  src/Components/UserProfile.jsx
  src/Containers/CadView.jsx
Labels: enhancement

#1133 Introduce cy-parallel pkg script
  .gitignore
  cypress.config.js
  cypress/e2e/parallel.sh
  package.json
  src/Containers/OperationsGroupAndDrawer.jsx
Labels: enhancement

#1139 open-100: Open Project From GitHub Link
  cypress/e2e/open-100/open-project-from-gh-link.cy.js
  cypress/e2e/open-100/open-sample-model.cy.js
  cypress/support/models.js
  package.json
  src/Components/Search/SearchBar.jsx
Labels: enhancement

#1141 view-100/synchronized-view-and-navtree.cy.js
  cypress/e2e/view-100/synchronized-view-and-navtree.cy.js
  cypress/support/utils.js
  package.json
Labels: enhancement

#1140 OPFS fix + move file context to zustand store + write model on save
  src/BaseRoutes.jsx
  src/Components/Open/OpenModelDialog.jsx
  src/Components/Open/SaveModelControl.jsx
  src/Containers/CadView.jsx
  src/Containers/CadView.test.jsx
  src/OPFS/FileContext.js
  src/OPFS/OPFS.worker.js
  src/OPFS/OPFSService.js
  src/OPFS/utils.js
  src/Share.jsx
  src/__mocks__/api-handlers.js
  src/store/AppSlice.js
Labels: bug, enhancement

#1143 Auth0 Proxy + Save e2e tests
  cypress/e2e/versions-100/save-imported-model.cy.js
  cypress/support/utils.js
  package.json
  src/Auth0/Auth0ProviderProxy.jsx
  src/Auth0/Auth0Proxy.js
  src/Auth0ProviderWithHistory.jsx
  src/Components/Profile/ProfileControl.jsx
Labels: enhancement

#1145 versions-100, notes-100: refactor to use helpers and nested contexts
  .gitignore
  cypress/e2e/notes-100/access-notes-list.cy.js
  cypress/e2e/notes-100/note-contains-link-to-github-issue.cy.js
  cypress/e2e/notes-100/select-a-note.cy.js
  cypress/e2e/notes-100/share-a-note.cy.js
  cypress/e2e/versions-100/save-imported-model.cy.js
  cypress/support/utils.js
  src/Components/Notes/NoteBody.jsx
  src/Components/Notes/NoteCard.jsx
  src/Components/Notes/NoteCard.test.jsx
  src/Components/Notes/Notes.jsx
  src/Containers/AlertDialogAndSnackbar.jsx
Labels: enhancement

#1147 conway-0.1.499: upgrade to include step loader
  bldrs-ai-conway-0.1.446.tgz
  bldrs-ai-conway-0.1.499.tgz
  cypress/e2e/open/100/open-project-from-gh-link.cy.js
  cypress/e2e/open/100/open-sample-model.cy.js
  cypress/e2e/open/200/open-step-model.cy.js
  cypress/e2e/parallel.sh
  cypress/fixtures/gear.step
  cypress/support/models.js
  package.json
  src/Containers/CadView.jsx
  yarn.lock
Labels: enhancement

#1152 cypress: use fixed port for cypress server
  cypress.config.js
  cypress/e2e/view-100/shareable-camera-position.cy.js
  package.json
Labels: bug

#1156 1134-first-time-about-doesnt-close-transient
  src/Components/About/AboutControl.jsx
Labels: bug

#1157 Percy script takes spec arg
  package.json
  tools/cy-percy.sh
Labels: enhancement

#1155 Show a specific version cypress test
  cypress/e2e/versions-100/show-specific-version.cy.js
  package.json
  src/Components/Versions/VersionsTimeline.jsx
  src/__mocks__/api-handlers.js
  src/net/github/Commits.fixture.js
  src/net/github/Commits.test.js
Labels: enhancement
