Repository bldrs-ai/Share, pull requests merged in 2024-02, with the labels that each got.

#959 OPFS fallback
  package.json
  src/Components/OpenModelControl.jsx
  src/Containers/CadView.jsx
  src/OPFS/utils.js
  src/utils/loader.js
  tools/esbuild/bundle-analysis.json
Labels: enhancement

#954 Add Issue link to the note
  src/Components/Buttons.jsx
  src/Components/Notes/NoteCardSupportComponents.jsx
  src/Components/Notes/NotesNavBar.jsx
  src/Components/Notes/NotesNavBar.test.jsx
Labels: notes

#958 small style fixes
  public/favicon.ico
  src/Components/ControlsGroup.jsx
  src/Components/HelpControl.jsx
  src/Components/SaveModelControl.jsx
  src/Components/SnackbarMessage.jsx
  src/assets/icons/SaveGraphic.svg
Labels: UI

#962 Activate save control only for authenticated users
  src/Components/ControlsGroup.jsx
Labels: UI

#977 Github + OPFS delete + OPFS tests
  package.json
  src/Components/OpenModelControl.jsx
  src/OPFS/OPFS.worker.js
  src/OPFS/OPFSService.js
  src/OPFS/utils.js
  src/OPFS/utils.test.js
  src/utils/GitHub.js
  src/utils/GitHub.test.js
Labels: enhancement

#987 Remove canvas from jest and pkgs.
  package.json
  tools/jest/setupTests.js
  yarn.lock
Labels: enhancement

#995 Fix for broken model load on private LFS from break in OPFS, also Ver…
  src/Components/Notes/NotesContol.jsx
  src/Containers/CadView.jsx
Labels: bug

#999 Update Conway v0.1.445
  bldrs-ai-conway-0.1.425.tgz
  bldrs-ai-conway-0.1.445.tgz
  package.json
  yarn.lock
Labels: enhancement

#1009 Address private model load with no AuthToken
  package.json
  src/Containers/CadView.jsx
  src/__mocks__/api-handlers.js
  src/utils/GitHub.js
  src/utils/GitHub.test.js
Labels: enhancement
