Repository bldrs-ai/Share, pull requests merged in 2024-03, with the labels that each got.

#1015 ISSUE_1003 Fix bug with parameter set up in getLatestCommitHash
  package.json
  src/OPFS/utils.js
  src/__mocks__/api-handlers.js
  src/utils/GitHub.js
  src/utils/GitHub.test.js
Labels: bug

#1016 Rollback camera-controls 1.38.2 -> 1.36.1
  package.json
  yarn.lock
Labels: bug

#1019 Private LFS Fix Issue 1014
  package.json
  src/utils/GitHub.js
  src/utils/GitHub.test.js
  src/utils/location.js
  src/utils/location.test.js
Labels: bug

#1020 Update Conway v0.1.445 to v0.1.446
  bldrs-ai-conway-0.1.445.tgz
  bldrs-ai-conway-0.1.446.tgz
  package.json
  yarn.lock
Labels: enhancement

#1021 Prepare for new web-ifc-viewer build
  package.json
  src/Components/ImagineControl.jsx
Labels: code

#1028 Add cypress projectId to cypress.config.js
  cypress.config.js
Labels: enhancement

#1029 Cypress tests running after a couple disabled; pkg script cypress:open -> cypress
  cypress/e2e/appStore/appStore.cy.js
  cypress/e2e/home/homepage.cy.js
  package.json
Labels: bug

#1050 1031 initial model load and view
  .gitattributes
  .github/workflows/end-to-end-tests.yml
  __mocks__/web-ifc-viewer.js
  cypress.config.js
  cypress/e2e/view-100/initial-model-load-and-view.cy.js
  cypress/fixtures/index.ifc
  cypress/plugin/index.js
  cypress/screenshots/initial-model-load-and-view.cy.js/initial-model-load-and-view -- Open model by following a link to a project on Share (e.g. our index.ifc) -- See model centered in page (cookie isFirstTime 1).png
  cypress/screenshots/initial-model-load-and-view.cy.js/initial-model-load-and-view -- Open model by following a link to a project on Share (e.g. our index.ifc) -- See model centered in page (cookie isFirstTime undefined).png
  package.json
  src/Components/Buttons.jsx
  src/Components/Dialog.jsx
  src/Components/HelpControl.jsx
  src/Components/HelpControl.test.jsx
  src/Components/OpenModelControl.jsx
  src/Containers/CadView.jsx
  src/store/AppSlice.js
  src/store/UISlice.js
  src/theme/Theme.jsx
  tools/esbuild/common.js
  tools/esbuild/esbuild.test.js
  tools/imgdiff.sh
  yarn.lock
Labels: enhancement

#1080 Revert 1074, prod fix
  package.json
  src/BaseRoutes.jsx
  src/Components/Open/OpenModelControl.jsx
  src/Components/Open/SaveModelControl.jsx
  src/Components/Open/SelectorSeparator.jsx
  src/Containers/CadView.jsx
  src/Containers/CadView.test.jsx
  src/OPFS/FileContext.js
  src/OPFS/OPFS.worker.js
  src/OPFS/OPFSService.js
  src/OPFS/utils.js
  src/OPFS/utils.test.js
  src/Share.jsx
  src/store/AppSlice.js
  src/store/OpfsSlice.js
  src/store/useStore.js
  src/utils/loader.js
Labels: bug
