Repository bldrs-ai/Share, pull requests merged in 2024-12, with the labels that each got.

#1274 cutplanes: fix regression that broke Clear All in #1271
  package.json
  src/Components/CutPlane/CutPlaneMenu.jsx
Labels: bug

#1275 samples: replace Eisvogel with Vitruvius (fbx robot model)
  package.json
  src/Components/Open/SampleModelFileSelector.jsx
  src/Components/Open/SampleModels.jsx
  src/assets/icons/vitruvian-man.webp
  src/pages/share/About.jsx
Labels: enhancement

#1272 NavTree performance upgrade
  package.json
  src/Components/NavTree/NavTree.test.jsx
  src/Components/NavTree/NavTreeItem.jsx
  src/Components/NavTree/NavTreeNode.jsx
  src/Components/NavTree/NavTreePanel.jsx
  src/Components/NavTree/PropTypes.js
  src/Components/NavTree/TypesNavTree.test.jsx
  src/Containers/NavTreeAndVersionsDrawer.test.jsx
  yarn.lock
Labels: enhancement

#1277 UI fixes
  package.json
  public/widgets/event-logger.html
  src/Components/Apps/AppsRegistry.json
  src/Components/NavTree/NavTreePanel.jsx
  src/Components/Search/SearchBar.jsx
  src/Containers/TabbedPanels.jsx
Labels: bug

#1283 apps: added back button in AppPanel
  cypress/e2e/apps/apps.cy.js
  cypress/e2e/screenshot/screen-from-note.cy.js
  package.json
  src/Components/Apps/AppEntry.jsx
  src/Components/Apps/AppIFrame.jsx
  src/Components/Apps/AppPanel.jsx
  src/Components/Apps/AppsListing.jsx
  src/Components/Apps/AppsPanel.jsx
  src/Components/Apps/AppsRegistry.json
  src/Components/Apps/component.js
  src/Components/SideDrawer/Panel.jsx
  src/Containers/AppsSideDrawer.jsx
  src/Containers/TabbedPanels.jsx
  tools/esbuild/serve.js
  yarn.lock
Labels: bug

#1284 buttons: Fix theme of BackButton
  package.json
  src/Components/Buttons.jsx
Labels: bug

#1290 conway: npm for conway-web-ifc-adapter, conway 0.3.695
  package.json
  scripts/netlify-preinstall.js
  yarn.lock
Labels: enhancement

#1293 1291 notes logged in user opens notes
  cypress/e2e/notes-100/access-notes-list.cy.js
  src/Components/Notes/NotesNavBar.jsx
Labels: enhancement

#1297 versions: fix mobile VersionPanel display. percy
  cypress/support/commands.js
  package.json
  src/Components/Versions/VersionsControl.jsx
  src/Components/Versions/VersionsPanel.jsx
  src/Components/Versions/VersionsPanel.test.jsx
  src/Components/Versions/component.js
  src/Containers/TabbedPanels.jsx
  src/Share.jsx
  src/store/VersionsSlice.js
Labels: bug

#1294 1287 Fix over scroll on mobile
  src/Containers/TabbedPanels.jsx
Labels: enhancement

#1299 Theme tweaks
  package.json
  src/Components/About/AboutDialog.jsx
  src/Components/NavTree/NavTree.jsx
  src/Components/NavTree/NavTree.test.jsx
  src/Components/NavTree/NavTreeItem.jsx
  src/Components/NavTree/NavTreeNode.jsx
  src/Components/NavTree/NavTreePanel.jsx
  src/Components/NavTree/PropTypes.js
  src/Components/NavTree/TypesNavTree.jsx
  src/Components/NavTree/TypesNavTree.test.jsx
  src/Components/SideDrawer/Panel.jsx
  src/Components/SideDrawer/PanelTitle.jsx
  src/Components/SideDrawer/SideDrawer.jsx
  src/Components/SideDrawer/VerticalResizerButton.jsx
  src/Components/Versions/VersionsTimeline.jsx
  src/Containers/RootLandscape.jsx
  src/Containers/TabbedPanels.jsx
  src/store/SideDrawerSlice.jsx
  src/theme/Components.js
  src/theme/Palette.js
Labels: bug, enhancement

#1302 Fix: 1300-sharing-removes-cut-plane
  package.json
  src/Components/CutPlane/CutPlaneMenu.jsx
  src/Components/CutPlane/hashState.js
  src/Containers/CadView.test.jsx
Labels: bug

#1304 /share/about: add YouTube Share intro
  src/pages/share/About.jsx
Labels: enhancement

#1305 cleanup: Remove unused @iconscout/react-unicons package
  package.json
  src/Components/Buttons.jsx
  src/Components/Imagine/ImagineDialog.jsx
  src/Components/InputBar.jsx
  src/Components/buttons/RectangularButton.stories.jsx
  yarn.lock
Labels: enhancement

#1308 Address Issue 1296
  package.json
  src/Containers/TabbedPanels.jsx
  src/Containers/TabbedPanels.test.jsx
Labels: enhancement

#1309 LICENSE.md: AGPLv3
  LICENSE.md
Labels: documentation

#1310 1281-properties-ux
  src/Components/NavTree/NavTreeNode.jsx
  src/Components/Properties/ExpansionPanel.jsx
  src/Components/Properties/Properties.jsx
  src/Components/Properties/itemProperties.jsx
  src/Containers/AlertDialogAndSnackbar.jsx
  src/assets/icons/NodeClosed.svg
  src/assets/icons/NodeOpened.svg
  src/theme/Components.js
  src/theme/Typography.js
Labels: bug

#1313 Fix sample models chip padding
  cypress/e2e/open/100/open-sample-model.cy.js
  package.json
  src/Components/Open/SampleModels.jsx
  src/theme/Components.js
Labels: bug
