Repository bldrs-ai/Share, pull requests merged in 2024-05, with the labels that each got.

#1158 1144 navtree not scrolling to selected elt of large tree
  .eslintrc.js
  package.json
  src/Components/HideToggleButton.jsx
  src/Components/NavTree/NavTree.jsx
  src/Components/NavTree/NavTree.test.jsx
  src/Components/NavTree/NavTreeItem.jsx
  src/Components/NavTree/NavTreePanel.jsx
  src/Components/NavTree/PropTypes.js
  src/Components/NavTree/TypesNavTree.jsx
  src/Components/NavTree/TypesNavTree.test.jsx
  src/Components/Properties/Properties.jsx
  src/Components/SideDrawer/Panel.jsx
  src/Containers/CadView.jsx
  src/Containers/selection.js
  src/theme/Components.js
  src/utils/IfcMock.test.js
  src/utils/TreeUtils.js
  src/utils/ifc.js
  src/utils/ifc.test.js
  src/utils/itemProperties.jsx
Labels: bug

#1161 Open 100: open model on GH via open UI and versions 100: edit-a-model
  cypress/e2e/open/100/open-model-from-gh-ui.cy.js
  cypress/e2e/versions-100/edit-a-model.cy.js
  package.json
  src/__mocks__/api-handlers.js
Labels: enhancement

#1162 conway-0.1.499 -> conway-0.1.510-1
  bldrs-ai-conway-0.1.499.tgz
  bldrs-ai-conway-0.1.510-1.tgz
  package.json
  yarn.lock
Labels: enhancement

#1168 Fix Issue1165
  package.json
  src/Share.jsx
Labels: bug

#1169 #1058 Notes 100 - Delete a note
  cypress/e2e/notes-100/delete-a-note.cy.js
  src/net/github/Issues.fixture.js
Labels: UX

#1173 conway 0.1.510-1 -> 0.1.513
  bldrs-ai-conway-0.1.513.tgz
  package.json
  yarn.lock
Labels: bug

#1163 Notes 100: Create a note
  cypress/e2e/notes-100/create-a-note.cy.js
  src/Components/Notes/NotesPanel.jsx
Labels: enhancement

#1170 Notes 100: Comments on notes
  cypress/e2e/notes-100/access-shared-note.cy.js
  cypress/e2e/notes-100/comments-on-a-note.cy.js
  cypress/e2e/notes-100/note-contains-link-to-github-issue.cy.js
  cypress/e2e/notes-100/select-a-note.cy.js
  package.json
  src/Components/Notes/NoteCard.jsx
  src/Components/Notes/NoteCardCreate.jsx
  src/Components/Notes/NoteFooter.jsx
  src/Components/Notes/Notes.jsx
  src/Components/Notes/NotesControl.jsx
  src/__mocks__/api-handlers.js
  src/net/github/Comments.fixture.js
  src/net/github/Comments.test.js
  src/store/NotesSlice.js
Labels: enhancement

#1183 CadView: fix resetState bugs
  __mocks__/web-ifc-viewer.js
  cypress/e2e/notes-100/access-shared-note.cy.js
  cypress/e2e/open/100/open-sample-model.cy.js
  package.json
  src/Components/CutPlane/CutPlaneMenu.jsx
  src/Components/OperationsGroup.jsx
  src/Containers/CadView.jsx
  src/Containers/CadView.test.jsx
  src/Share.jsx
  src/store/AppSlice.js
  tools/esbuild/vars.prod.js
Labels: bug

#1184 Create-a-Note test fix
  cypress/e2e/notes-100/create-a-note.cy.js
  src/Components/Notes/NoteCardCreate.jsx
  src/store/NotesSlice.js
Labels: bug

#1179 Open 200 - Tabbed Open dialog
  cypress/e2e/open/100/open-model-from-gh-ui.cy.js
  cypress/e2e/open/100/open-sample-model.cy.js
  cypress/e2e/open/200/open-model-dialog.cy.js
  package.json
  src/Components/Open/GitHubFileBrowser.jsx
  src/Components/Open/GitHubFileBrowser.test.jsx
  src/Components/Open/OpenModelControl.jsx
  src/Components/Open/OpenModelControl.test.jsx
  src/Components/Open/OpenModelDialog.jsx
  src/Components/Open/PleaseLogin.jsx
  src/Components/Open/SampleModels.jsx
  src/Components/Open/SaveModelControl.test.jsx
  src/Components/Tabs.jsx
  src/assets/icons/Bldrs.svg
  src/assets/icons/Eisvogel.svg
  src/assets/icons/Momentum.svg
  src/assets/icons/Placeholder.svg
  src/assets/icons/Question.svg
  src/assets/icons/Seestrasse.svg
  src/assets/icons/Sheenstock.svg
  src/store/OpenSlice.js
  src/theme/Components.js
  src/theme/Palette.js
Labels: enhancement

#1197 conway-0.1.543
  bldrs-ai-conway-0.1.510-1.tgz
  bldrs-ai-conway-0.1.513.tgz
  bldrs-ai-conway-0.1.543.tgz
  package.json
  web-ifc-viewer-1.0.209-bldrs-2.tgz
  web-ifc-viewer-1.0.209-bldrs-3.tgz
  yarn.lock
Labels: enhancement

#1198 open-200: support .stp and .step URLs
  cypress/e2e/open/200/open-step-model.cy.js
  package.json
  src/Containers/CadView.jsx
  src/Filetype.js
  src/Filetype.test.js
Labels: enhancement

#1199 node: require node >18
  .github/workflows/end-to-end-tests.yml
  .github/workflows/main.yml
  package.json
Labels: enhancement

#1167 Network Caching System + Octokit Version Upgrade + Node 18 Upgrade
  package.json
  src/net/github/Cache.js
  src/net/github/Files.js
  src/net/github/Http.js
  tools/jest/jest.config.js
  tools/jest/setupNodeFetch.cjs
  yarn.lock
Labels: bug
