Repository bldrs-ai/Share, pull requests merged in 2024-01, with the labels that each got.

#913 OAuth Github Login with Popup
  package.json
  src/Components/LoginMenu.jsx
  tools/esbuild/bundle-analysis.json
Labels: enhancement

#925 Replace FixtureContext with more fine-grained contexts.
  package.json
  src/Components/About/AboutDialog.fixture.jsx
  src/Components/Dialog.fixture.jsx
  src/Components/InputAutocomplete.fixture.jsx
  src/Components/Loader.fixture.jsx
  src/Components/Notes/NoteCardCreate.jsx
  src/Components/TabbedDialog.fixture.jsx
  src/Components/TableRow.fixture.jsx
  src/Components/Tabs.fixture.jsx
  src/Components/Timeline.fixture.jsx
  src/Components/Toast.fixture.jsx
  src/Components/TooltipIconButton.fixture.jsx
  src/Components/buttons/ControlButton.fixture.jsx
  src/FixtureContext.jsx
  src/Share.fixture.jsx
  src/store/Store.fixture.jsx
  src/store/Store.test.jsx
  src/theme/Theme.fixture.jsx
  src/theme/Theme.test.jsx
  tools/esbuild/bundle-analysis.json
Labels: enhancement

#938 Fix login menu position.
  src/Components/ImagineControl.jsx
  src/Components/LoginMenu.jsx
Labels: bug, UI

#943 Application error component style
  src/Components/ApplicationError.jsx
Labels: UI
