Repository bldrs-ai/Share, pull requests merged in 2024-07, with the labels that each got.

#1225 notes: reduce gh api usage by delay of gh issues fetch until notes are open
  package.json
  src/Components/Notes/NotesControl.jsx
  src/Components/Notes/NotesControl.test.jsx
Labels: bug

#1228 open: reduce gh api usage by delay of gh orgs fetch until open/save dialog is open
  package.json
  src/Components/Notes/NotesControl.test.jsx
  src/Components/Open/OpenModelControl.jsx
  src/Components/Open/OpenModelControl.test.jsx
  src/Components/Open/SaveModelControl.jsx
  src/Components/Open/SaveModelControl.test.jsx
  src/store/UISlice.js
Labels: bug

#1230 fix open dialog repo filtering
  src/Components/Open/GitHubFileBrowser.jsx
Labels: bug

#1239 Disable nav tree activation on the element select
  cypress/e2e/view-100/synchronized-view-and-navtree.cy.js
  src/Components/NavTree/NavTreeControl.jsx
  src/Components/NavTree/NavTreeControl.test.jsx
Labels: bug

#1247 Change request timeout from 5 to 10 seconds
  package.json
  src/net/github/Http.js
Labels: enhancement

#1240 View 100: Access Element's Properties
  cypress/e2e/view-100/access-element-properties.cy.js
  package.json
  src/Components/Properties/ExpansionPanel.jsx
  src/Components/Properties/Properties.jsx
  src/theme/Components.js
  src/utils/itemProperties.jsx
Labels: story
