Repository bldrs-ai/Share, pull requests merged in 2025-03, with the labels that each got.

#1339 Fix Auth0 Popup Login
  package.json
  src/Auth0/Auth0ProviderProxy.jsx
  src/Auth0/Auth0Proxy.js
  src/Auth0ProviderWithHistory.jsx
  src/BaseRoutes.jsx
  src/Components/Auth/PopupAuth.jsx
  src/Components/Auth/PopupCallback.jsx
  src/Components/Profile/ProfileControl.jsx
  yarn.lock
Labels: enhancement

#1340 Downgrade conway to stable version
  package.json
  yarn.lock
Labels: bug, enhancement

#1341 Update conway version fix regression
  package.json
  yarn.lock
Labels: enhancement

#1347 Disable http caching on /contents endpoint
  package.json
  src/net/github/Files.js
  src/net/github/Http.js
Labels: bug, enhancement

#1345 sentry: upgrade 7.61.0->9.5.0
  .github/workflows/end-to-end-tests.yml
  package.json
  src/index.jsx
  yarn.lock
Labels: enhancement

#1350 fix #68, double-escaping github paths
  package.json
  src/net/github/Http.js
  src/net/github/Http.test.js
Labels: bug

#1335 Re-enable GA
  public/index.html
  src/BaseRoutes.jsx
  src/Components/About/AboutControl.jsx
  src/Components/About/AboutDialog.jsx
  src/Components/Logo/Logo.jsx
  src/Components/Open/OpenModelControl.jsx
  src/hooks/usePageTracking.jsx
  src/hooks/usePageTracking.test.jsx
Labels: enhancement
