Repository bldrs-ai/Share, pull requests merged in 2025-05, with the labels that each got.

#1361 Fix loal file open URL and item selection crash (#1333)
  cypress/e2e/open/100/open-model-dialog.cy.js
  src/Containers/CadView.jsx
  src/utils/loader.js
Labels: bug

#1365 conway: 0.18.886 -> 0.21.911
  package.json
  yarn.lock
Labels: enhancement

#1370 A few fixes
  package.json
  public/icons/speedtest.png
  public/speedtest.png
  src/Components/Notes/NoteContent.jsx
  src/Components/Search/SearchBar.jsx
  src/Containers/ControlsGroup.jsx
  src/Containers/NotesAndPropertiesDrawer.test.jsx
  src/net/github/Issues.fixture.js
  src/pages/share/About.jsx
  src/pages/share/Conway.jsx
  src/store/SideDrawerSlice.jsx
Labels: bug

#1373 1369 error unsupported filetype ifc upper case via file open
  package.json
  src/Filetype.js
  src/Filetype.test.js
Labels: bug

#1376 Updates to get codex working, and first test fix
  package.json
  src/utils/strings.js
  src/utils/strings.test.js
  yarn.lock
Labels: enhancement, codex

#1379 src/utils/location.test.js and src/OPFS/utils.js
  src/OPFS/utils.js
  src/utils/loader.test.js
Labels: bug, codex

#1380 Disable share for local models
  src/Share.jsx
  src/__mocks__/api-handlers.js
  src/store/RepositorySlice.js
  src/store/useStore.test.js
Labels: codex

#1374 ISSUE1371 Fix
  src/OPFS/OPFS.worker.js
  src/OPFS/OPFS.worker.test.js
Labels: enhancement
