Repository bldrs-ai/Share, pull requests merged in 2025-06, with the labels that each got.

#1382 Allow selecting git branch in open & save flows
  cypress/e2e/versions-100/save-imported-model.cy.js
  package.json
  src/Components/Open/GitHubFileBrowser.jsx
  src/Components/Open/GitHubFileBrowser.test.jsx
  src/Components/Open/SaveModelControl.jsx
  src/Components/Open/SaveModelControl.test.jsx
  src/OPFS/utils.js
  src/__mocks__/api-handlers.js
  src/net/github/Branches.js
  src/net/github/Files.js
  src/net/github/Http.js
Labels: codex

#1383 Cleanup: remove .npmrc from GHA, normalize github fixture shapes, common HTTP_* defs
  .github/workflows/end-to-end-tests.yml
  .github/workflows/main.yml
  .npmrc
  package.json
  scripts/netlify-preinstall.js
  src/Components/Versions/useVersions.test.jsx
  src/OPFS/OPFS.worker.js
  src/__mocks__/api-handlers.js
  src/loader/Loader.js
  src/net/github/Commits.fixture.js
  src/net/github/Files.fixture.js
  src/net/github/Files.js
  src/net/github/Files.test.js
  src/net/github/Http.js
  src/net/github/Http.test.js
  src/net/github/Issues.test.js
  src/net/http.js
Labels: code

#1384 Save: wrap file save operation in try/catch/throw to set error message
  src/Components/Dialog.jsx
  src/Components/Open/SaveModelControl.jsx
Labels: bug

#1388 conway: 0.22.921 -> 0.23.940
  package.json
  yarn.lock
Labels: enhancement
